name: Deploy Project
on: [workflow_dispatch]
jobs:
  info:
    runs-on: ubuntu-latest
    steps: 
      - name: Print Context
        run: echo "${{ toJSON(github) }}"
  prepare-code:
    needs: info
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm install
      - name: lint
        run: npm run lint
      - name: Test
        run: npm run test
      - name: Build
        run: npm run build
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: dist-files
          path: dist
  deploy-code:
    needs: prepare-code
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifacts@v3
        with:
          name: dist-files
      - name: List files
        run: ls
      - name: Deploy
        run: echo "Deploying ..."
