name: Matrix Jobs
on: [workflow_dispatch]
jobs:
  build:
    strategy:
      matrix: 
        node_versions: [14,16,18]
        strings: ["Hello", "World"]
        include: 
          - node_versions: 20
          - strings: "V20"
        exclude:
          - node_versions: 18
          - strings: "World"
        
    runs-on: ubuntu-latest
    steps: 
      - name: Get code
        uses: actions/checkout@v3
      - name: Print Text
        run: echo "${{ matrix.strings }}"
