name: Reusable Deploy
on: 
  workflow_call:
    inputs:
      x-coord:
        description: Location x coordinate
        default: 0.0
        type: string
        required: false
      y-coord:
        description: Location y coordinate
        default: 0.0
        type: string
        required: false
    secrets:
      api-key:
        description: key of the app
        required: true
    outputs:
      coordinates:
        value: ${{ jobs.deploy.outputs.coords }}
jobs:
  deploy:
    outputs:
      coords: ${{ steps.deploy.outputs.COORDS }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        id: deploy
        run: echo "COORDS=(${{ inputs.x-coord }}, ${{ inputs.y-coord }})" >> $GITHUB_OUTPUT
