name: Reusable Deploy
on: 
  workflow_call:
    inputs:
      x-coord:
        description: Location x coordinate
        default: 0.0
        type: string
        required: false
      y-coord:
        description: Location y coordinate
        default: 0.0
        type: string
        required: false
    secrets:
      api-key:
        description: key of the app
        required: true
    outputs:
      coordinate:
        description: The xy coordinate
        value: "(${{ inputs.x-coord }}, ${{ inputs.y-coord }})"
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        run: echo "Deployed to (${{ inputs.x-coord }}, ${{ inputs.y-coord }})"
