name: Second Workflow
on: [workflow_dispatch]
jobs:
  deploy:
    uses: ./.github/workflows/reusable.yml
    with: 
      x-coord: 10.5
      y-coord: 12.2
    secrets:
      api-key: "1234567"
  print-coord:
    needs: deploy
    runs-on: ubuntu-latest
    steps:
      - name: print
        run: echo "--->>> ${{ needs.deploy.outputs.coords }}"
      
