name: Third Workflow
on: [workflow_dispatch]
jobs:
  job-1:
    outputs:
      output1: ${{ steps.step1.outputs.test }}
      output2: ${{ steps.step2.outputs.test }}
    runs-on: ubuntu-latest
    steps:
      - name: set output
        id: step1
        run: echo "test=Hello" >> "$GITHUB_OUTPUT"
      - name: set output
        id: step2
        run: echo "test=World" >> "$GITHUB_OUTPUT"
  job-2:
    needs: job-1
    runs-on: ubuntu-latest
    steps:
      - env:
          TEXT1: ${{ needs.job-1.outputs.output1 }}
          TEXT2: ${{ needs.job-1.outputs.output2 }}
      - name: print output
        run: echo "$TEXT1 $TEXT2"
        
